[package]
name = "vm2-flipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
casper-macros = { path = "../casper-node/smart_contracts/macros" }
casper-sdk = { path = "../casper-node/smart_contracts/sdk" }
[profile.release]
codegen-units=1
opt-level="z"
lto=true
debug=false
panic="abort"
overflow-checks=true

